# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rank',
        ),
    ]
