# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 05:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_remove_comment_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anothercomments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
